config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'


  devise_for :users, 
             :path => '', 
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  resources :users, only: [:show]

  resources :things

  resources :photos

  resources :things do
    resources :rentals, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  get '/preload' => 'rentals#preload'
  get '/preview' => 'rentals#preview'
  get '/your_borrowings' => 'rentals#your_borrowings'
  get '/your_lendings' => 'rentals#your_lendings'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime('%v')
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_conversation

def index
	if current_user = @conversation.sender || @conversation.recipient
		@other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
		@messages = @conversation.messages.order('created_at DESC')
	else
		redirect_to conversations_path, alert: 'You don\'t have permision to view this'
	end

end

def create
	@message = @conversation.messages.new(message_params)
	@messages = @conversation.messages.order('created_at DESC')

	if @message.save
		respond_to do |format|
			format.js
		end
	end
end


private

	def set_conversation
		@conversation = Conversation.find(params[:conversation_id])
	end

	def message_params
		params.require(:message).permit(
			:content, 
			:user_id
		)
	end
end

app/views/messages/_message.html.erb
<div class="card-panel">
	<%= image_tag avatar_url(message.user), class: 'circle avatar_small' %>
	<strong><%= message.user.full_name %></strong>
	<<span><%= message.message_time %></span>
	<br />
	<div>
		<%= message.content %>
	</div>
</div>

app/views/messages/create.js.erb
<% publish_to conversation_messages_path(@conversation) do %>
	$('#chat').prepend('<%= j render (@message) %>');
<% end %>
$('#new_message')[0].reset();

app/views/messages/index.html.erb
<div class="row">
	<div class="col m3">
		<%= image_tag avatar_url(@other), class: 'circle avatar-small' %><br/>
		<strong><%= @other.full_name %></strong>
		<%= link_to 'View profile', @other, class: 'btn' %>
	</div>
	<div class="col m9">
		<div class="card-panel">
			<%= subscribe_to conversation_messages_path(@conversation) %>
			<h4>Conversation with <%= @other.full_name %></h4>
			<%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
				<div class="form-group">
					<%= f.text_area :content, placeholder: 'Add a message', class: 'form-control' %>	
				</div>
				<%= f.hidden_field :user_id, value: current_user.id %>
				<div class="actions">
					<%= f.submit 'Send message', class: 'btn' %>
				</div>
			<% end %>
		</div>
		<div id="chat">
			<%= render @messages, locals: {conversation: @conversation} %>
		</div>
	</div>
</div>