config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'


  devise_for :users, 
             :path => '', 
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  resources :users, only: [:show]

  resources :things

  resources :photos

  resources :things do
    resources :rentals, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  get '/preload' => 'rentals#preload'
  get '/preview' => 'rentals#preview'
  get '/your_borrowings' => 'rentals#your_borrowings'
  get '/your_lendings' => 'rentals#your_lendings'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	 <script type="text/javascript">
	 	<% resource.errors.full_messages.each do |msg| %>
	 	toastr.error('<%= msg %>')
	 	<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type='text/javascript'>
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->

  <nav class="navbar-fixed orange accent-3">
    <div class="nav-wrapper">
      <%= link_to 'Borrowmate', root_path, class: 'brand-logo' %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% else %>
          <li>
          </li>
          <li><%= link_to (raw('<i class="material-icons">message</i>')), conversations_path %></li>
          <li><%= link_to (raw('<i class="material-icons">library_add</i>')), new_thing_path, class: 'valign-wrapper' %></li>
            <a class="dropdown-button valign-wrapper" href="#" data-activates="dropdown1">
              <%= current_user.full_name %> <%= image_tag avatar_url(current_user), class: 'circle avatar-small' %> 
              <i class="material-icons right">arrow_drop_down</i>
            </a>
            <ul id="dropdown1" class="dropdown-content">
              <li><%= link_to (raw('<i class="material-icons">dashboard</i> My Full profile')), user_path(current_user) %></li>
              <li><%= link_to (raw('<i class="material-icons">games</i> My Things')), things_path %></li>
              <li><%= link_to (raw('<i class="material-icons">call_made</i> My Lendings')), your_lendings_path %></li> 
              <li><%= link_to (raw('<i class="material-icons">call_received</i> My Borrowings')), your_borrowings_path %></li>
              <li><a href="#"><i class="material-icons">loyalty</i>My wish list</a></li>
              <li><%= link_to (raw('<i class="material-icons">power_settings_new</i> Edit My Account')), edit_user_registration_path %></li>
              <li><%= link_to (raw('<i class="material-icons">error</i>Log out')), destroy_user_session_path, method: :delete %></li>
            </ul>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% else %>
          <li>
          </li>
          <li><%= link_to (raw('<i class="material-icons">message</i> <span>Messages</span>')) %></li>
          <li><%= link_to (raw('<i class="material-icons">library_add</i> <span>Add new thing</span>')), new_thing_path, class: 'valign-wrapper' %></li>
            <a class="dropdown-button2 valign-wrapper" href="#" data-activates="dropdown2">
              <%= current_user.full_name %> <%= image_tag avatar_url(current_user), class: 'circle avatar-small' %> 
              <i class="material-icons right">arrow_drop_down</i>
            </a>
            <ul id="dropdown2" class="dropdown-content">
              <li><%= link_to (raw('<i class="material-icons">dashboard</i> My Full profile')), user_path(current_user) %></li>
              <li><%= link_to (raw('<i class="material-icons">games</i> My Things')), things_path %></li>
              <li><%= link_to (raw('<i class="material-icons">call_made</i> My Lendings')), your_lendings_path %></li> 
              <li><%= link_to (raw('<i class="material-icons">call_received</i> My Borrowings')), your_borrowings_path %></li>
              <li><a href="#"><i class="material-icons">loyalty</i>My wish list</a></li>
              <li><%= link_to (raw('<i class="material-icons">power_settings_new</i> Edit My Account')), edit_user_registration_path %></li>
              <li><%= link_to (raw('<i class="material-icons">error</i>Log out')), destroy_user_session_path, method: :delete %></li>
            </ul>
        <% end %>
      </ul>

    </div>
  </nav>