config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'


  devise_for :users, 
             :path => '', 
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  resources :users, only: [:show]

  resources :things

  resources :photos

  resources :things do
    resources :rentals, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  get '/preload' => 'rentals#preload'
  get '/preview' => 'rentals#preview'
  get '/your_borrowings' => 'rentals#your_borrowings'
  get '/your_lendings' => 'rentals#your_lendings'

end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
	before_action :authenticate_user!

	def preload
		thing = Thing.find(params[:thing_id])
		today = Date.today
		rentals = thing.rentals.where("start_date >= ? OR end_date >= ?", today, today)

		render json: rentals
	end

	def preview
		start_date = Date.parse(params[:start_date])
		end_date = Date.parse(params[:end_date])

		output = {
			conflict: is_conflict(start_date, end_date)
		}

		render json: output
	end



	def create
		@rental = current_user.rentals.create(rental_params)
		redirect_to @rental.thing, notice: 'Your rental has been created'
	end

	def your_borrowings
		@borrowings = current_user.rentals
	end

	def your_lendings
		@things = current_user.things
	end

	private
		def is_conflict (start_date, end_date)
			thing = Thing.find(params[:thing_id])
			check = thing.rentals.where('? < start_date AND end_date < ?', start_date, end_date)
			check.size > 0? true: false
		end

		def rental_params
			params.require(:rental).permit(
				:start_date,
				:end_date,
				:price,
				:total,
				:thing_id
				)
		end
end

app/views/rentals/_form.html.erb
<%= form_for([@thing, @thing.rentals.new]) do |f| %>
	<div class="row">
		<div class="col m12 price_tag">
			<span>$<%= @thing.price %></span>
			<span class="pull-right">Per Night</span>
		</div>
	</div>
	<div class="row">
		<div class="col m6">
			<label>Borrow date</label>
			<%= f.text_field :start_date, readonly: 'true', placeholder: 'Borrow Date', class: 'form-control' %>
		</div>
		<div class="col m6">
			<label>Return date</label>
			<%= f.text_field :end_date, readonly: 'true', placeholder: 'Return Date', class: 'form-control', disabled: 'true' %>
		</div>
	</div>
	<%= f.hidden_field :thing_id, value: @thing.id %>
	<%= f.hidden_field :price, value: @thing.price %>
	<%= f.hidden_field :total, id: 'rental_total' %>

	<h4><span id="message"></span></h4>
	<div id="preview" style="display:none">

		<table class="rental-table">
			<tbody>
				<tr>
					<td>
						Day(s)
					</td>
					<td>
						<span id="rental_days"></span>
					</td>
				</tr>
				<tr>
					<td>
						Total
					</td>
					<td>
						$ <span id="rental_sum"></span>
					</td>
				</tr>
			</tbody>
		</table>
		<br/>
	</div>
	
	<%= f.submit 'Book now', id:'btn_book', class: 'btn btn-primary wide', disabled: true %>
	<br/><br/>
<% end %>
	

<script>

	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];
	}
	$(function() {

		unavailableDates = [];

		$.ajax({
			url: '/preload',
			data: {'thing_id': <%= @thing.id %>},
			dataType: 'json',
			success: function(data) {
				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
					}
				});
				$('#rental_start_date').datepicker ({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#rental_end_date').datepicker('option', 'minDate', selected);
						$('#rental_end_date').attr('disabled', false);

						var start_date = $(this).datepicker('getDate');
						var end_date = $('#rental_end_date').datepicker('getDate');
						var days = (end_date - start_date)/1000/60/60/24 + 1;
						var input = {
							'start_date': start_date,
							'end_date': end_date,
							'thing_id': <%= @thing.id %>
						}
						$.ajax ({
							url: '/preview',
							data: input,
							success: function(data) {
								if (data.conflict) {
									$('#message').text('This date range conflicts with another booking');
									$('#preview').hide();
									$('#btn_book').attr('disabled',true);
								} else {
									$('#preview').show();
									$('#btn_book').attr('disabled',false);

									var total = days * <%= @thing.price %>
									$('#rental_days').text(days);
									$('#rental_sum').text(total);
									$('#rental_total').val(total);
								}

							}
						});
					}
				});
				$('#rental_end_date').datepicker ({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#rental_start_date').datepicker('option', 'maxDate', selected);

						var start_date = $('#rental_start_date').datepicker('getDate');
						var end_date = $(this).datepicker('getDate');
						var days = (end_date - start_date)/1000/60/60/24 + 1;
						var input = {
							'start_date': start_date,
							'end_date': end_date,
							'thing_id': <%= @thing.id %>
						}
						$.ajax ({
							url: '/preview',
							data: input,
							success: function(data) {
								if (data.conflict) {
									$('#message').text('This date range conflicts with another booking');
									$('#preview').hide();
									$('#btn_book').attr('disabled',true);
								} else {
									$('#preview').show();
									$('#btn_book').attr('disabled',false);

									var total = days * <%= @thing.price %>
									$('#rental_days').text(days);
									$('#rental_sum').text(total);
									$('#rental_total').val(total);
								}

							}
						});
					}
				});
			}
		})
	});
</script>

app/views/rentals/_sidebar.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to 'My things', things_path, class: 'sidebar-link active' %>
	</li>
	<li class="sidebar-item">
		<%= link_to 'My lendings', your_lendings_path, class: 'sidebar-link' %>
	</li>	
	<li class="sidebar-item">
		<%= link_to 'My borrowings', your_borrowings_path, class: 'sidebar-link' %>
	</li>	
</ul>

app/views/rentals/your_borrowings.html.erb
<div class="row">
	<div class="col m3">
		<%= render 'sidebar' %>
	</div>
	<div class="col m9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your borrowings
			</div>
			<div class="panel-body">
				<% @borrowings.each do |borrowing| %>
					<div class="row">
						<div class="col m2">
							<%= borrowing.start_date.strftime('%v') %>
						</div>
						<div class="col m6">
							<%= link_to thing_path(borrowing.thing) do %>
								<%= image_tag borrowing.thing.photos[0].image.url(:thumb) if borrowing.thing.photos.length > 0%>
							<% end %>
						</div>
						<div class="col m2">
							<%= link_to user_path(borrowing.thing.user) do %>
								<%= image_tag avatar_url(borrowing.thing.user), class: 'img-circle avatar_medium' %>
							<% end %>
						</div>
						<div class="col m2 right">
							$<%= borrowing.total %>
						</div>
					</div>
					<hr>	
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rentals/your_lendings.html.erb
<div class="row">
	<div class="col m3">
		<%= render 'sidebar' %>
	</div>
	<div class="col m9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Lendings
			</div>
			<div class="panel-body">
				<% @things.each do |thing| %>
					<% thing.rentals.each do |rental| %>
						<div class="row">
							<div class="col m2">
								<%= rental.start_date.strftime('%v') %>
							</div>
							<div class="col m6">
								<%= link_to thing_path(rental.thing) do %>
									<%= image_tag rental.thing.photos[0].image.url(:thumb) if rental.thing.photos.length > 0%>
								<% end %>
							</div>
							<div class="col m2">
								<%= link_to user_path(rental.user) do %>
									<%= image_tag avatar_url(rental.user), class: 'img-circle avatar_medium' %>
								<% end %>
							</div>
							<div class="col m2 right">
								$<%= rental.total %>
							</div>
						</div>
						<hr>	
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>